shared:

resource_types:
  - name: habitat-builder
    type: docker-image
    privileged: true
    source:
      repository: jdvogt/hab-pkg-build-resource
      tag: latest
  - name: habitat-package-promoter
    type: docker-image
    source:
      repository: jonlives/hab-resource
      tag: latest
  
resources:
  - name: bldr-chef-linux-hardening-demo
    type: habitat-package-promoter
    source:
      origin: jvdemo
      name: national-parks
      channel: unstable
      auth_token: _Qk9YLTEKYmxkci0yMDE3MDkyNzAyMzcxNApibGRyLTIwMTcwOTI3MDIzNzE0Cmp6ZmJaRGVmQ3BEQVlKN0tTKzlTdG9oUXAyM3BpR2h6CitMQ2ZFYmpDN1dqTjltTEZ1ejRTaXAwTXAwRFVEMHBVTEpIQjJaRWJhUHQ2bDVBSw==

  - name: git-repo
    type: git
    source:
      uri: https://github.com/jvogt/habitat-national-parks-demo.git
      branch: master

jobs:
  - name: Change Detected in App Code Repo
    plan:
      - get: git-repo
        trigger: true
  - name: Code Test
    plan:
      - get: git-repo
        trigger: true
        passed: ["Change Detected in App Code Repo"]
      - task: Lint / Syntax / Unit Testing
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["Running tests"]
            
  - name: Kitchen Test - Compliance
    plan:
      - get: git-repo
        trigger: true
        passed: ["Code Test"]
      - task: Test Compliance
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["kitchen test disabled for demo"]

  - name: Build Package
    plan:
    - get: git-repo
      trigger: true
      passed: ["Kitchen Test - Compliance"]
    - task: Build Package
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: jdvogt/hab-pkg-build-resource}

        inputs:
          - name: git-repo

        outputs:
          - name: results

        run:
          path: sh
          args:
            - -exc
            - |
              cd git-repo
              keys_cache=$(mktemp -d /tmp/hab_cache_keys_path.XXXXXX)
              trap "rm -rf ${keys_cache}" INT QUIT TERM EXIT
              export HAB_CACHE_KEY_PATH=${keys_cache}

              export HAB_ORIGIN=jvdemo
              export HAB_AUTH_TOKEN=_Qk9YLTEKYmxkci0yMDE3MDkyNzAyMzcxNApibGRyLTIwMTcwOTI3MDIzNzE0Cmp6ZmJaRGVmQ3BEQVlKN0tTKzlTdG9oUXAyM3BpR2h6CitMQ2ZFYmpDN1dqTjltTEZ1ejRTaXAwTXAwRFVEMHBVTEpIQjJaRWJhUHQ2bDVBSw==

              hab origin key generate $HAB_ORIGIN

              hab pkg build habitat
              . results/last_build.env
              hab pkg upload results/$pkg_artifact

  - name: Promote to Production?
    plan:
    - get: git-repo
      trigger: false
      passed: ["Build Package"]

  - name: Promote to Production
    plan:
    - get: git-repo
      trigger: true
      passed: ["Promote to Production?"]
    - get: bldr-chef-linux-hardening-demo
      trigger: true
    - put: bldr-chef-linux-hardening-demo
      params: {promote_to: stable}
 