shared:

resource_types:
  - name: habitat-package-promoter
    type: docker-image
    source:
      repository: jonlives/hab-resource
      tag: latest
  
resources:
  - name: prod-chef-pkg
    type: habitat-package-promoter
    source:
      origin: jvdemo
      name: chef-linux-hardening-demo
      channel: stable

jobs:
  - name: Change Detected in Production Chef Code Package
    plan:
      - get: prod-chef-pkg
        trigger: true
  - name: Build Public VM
    plan:
      - get: prod-chef-pkg
        trigger: true
        passed: ["Change Detected in Production Chef Code Package"]
      - task: Build Public VM
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["Building Public VM"]
    
  - name: Apply Chef Code
    plan:
      - get: prod-chef-pkg
        trigger: true
        passed: ["Build Public VM"]
      - task: Apply Chef Code
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["Apply Chef Code"]
  
  - name: Test Compliance
    plan:
      - get: prod-chef-pkg
        trigger: true
        passed: ["Apply Chef Code"]
      - task: Test Compliance
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["Test Compliance"]

  - name: Save Image and Upload
    plan:
      - get: prod-chef-pkg
        trigger: true
        passed: ["Test Compliance"]
      - task: Save Image and Upload
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          run:
            path: echo
            args: ["Save image and upload"]
